logic:
  managed_album: All
  group_checker:
    stats:
      required_tag: photography
      delay: 120
    selector:
      initial_burst:
        num_photos: 3
        min_tier: 3
      switch_phase:
        required_photos: 10
        min_tier: 3
      dump_phase:
        max_tier: 3
  publisher:
    queue_album: Queue
    showcase_album: Showcase
    time_window_start: 8
    time_window_end: 11
  reorderer:
    enabled: false
    days_until_being_ordered: 7
  greylist:
    group:
      photo_added: 16
    photo:
      added_to_group: 24
      published: 4
    publish:
      published10: 68
      published15: 40
      published: 20
    ordering:
      photos_ordered: 24
applicator:
  greylist:
    max_attempts: 14
    timeout: 24
  throttle:
    min_ms: 2000
    max_ms: 10000
